# Generated by Django 5.2 on 2025-06-24 02:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_boleta_fecha_remove_boleta_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='boleta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='boleta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordendespacho',
            name='boleta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ventas.boleta'),
        ),
        migrations.AddField(
            model_name='ordendespacho',
            name='direccion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.carrito'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ventas.producto'),
        ),
    ]
